### ISSUE TITLE
디시인사이드 갤러리 글 수정 문제

### ISSUE THREAD

**Issue by tjtnsgns** [NativeHyun/HyunGuard#28]
제가 디시인사디드 포켓몬 갤러리를 자주 가는 데 거기에 글은 써지는 데 수정이나 삭제등의  있는 라인이 사라져 있습니다 수정부탁드립니다

**Comment by NativeHyun** [comment]
안녕하세요! 이메일 알림을 보고 왔더니 제가 여기를 업데이트 못한지도 좀 됬네요.. 요즘들어 제가 수능 준비 및 입시 때문에 관리를 하지 못했습니다. 불편하시겠지만 제가 수능 끝나고 다시 필터 업데이트를 시작할때까지는 디시인사이드를 허용 리스트에 넣고 사용해주시길 부탁드립니다. 입시가 끝난 후 수정하도록 하겠습니다. 소중한 피드백 감사합니다! 좋은 하루 보내세요 :)

**Comment by tjtnsgns** [comment]
필터 업데이트를 했는 대도 아직 제대로 되지 않습니다. 수정부탁드립니다
![sd](https://user-images.githubusercontent.com/28147257/33511377-14097310-d75d-11e7-9981-07ad0c79720d.jpg)
![Uploading 익스.jpg…]()

**Comment by NativeHyun** [comment]
안녕하세요. 제가 직접 디시인사이드 포켓몬 갤러리에 방문하고 글 보기 페이지에서 어떤 필터가 작동하는지 확인도 해보았으나 글 라인이 사라지는 문제가 제 크롬에서는 재현되지 않고 있습니다. (필터 적용 상태) 다른 필터를 같이 사용중이시라면 다른 필터를 끄고 확인해주실수 있을까요?

![dddd](https://user-images.githubusercontent.com/17329096/33512426-a4efd21e-d773-11e7-9b38-eb54a349031b.png)

**Comment by tjtnsgns** [comment]
다시 확인 결과 멀웨이랑 HyunGuard‎ 필터랑 dc사이트랑 부딧친 것 같습니다. 멀웨이들 정리하니 되네여.
![as](https://user-images.githubusercontent.com/28147257/33730665-0ee0aabe-dbc4-11e7-8775-31dadc484a55.jpg)
![as_00000](https://user-images.githubusercontent.com/28147257/33730667-0f3d5c50-dbc4-11e7-82eb-6bcb24772956.jpg)
