### ISSUE TITLE
모바일 네이버 뉴스에서의 문제

### ISSUE THREAD

**Issue by tgpark** [NativeHyun/HyunGuard#3]
모바일 네이버 뉴스( http://m.news.naver.com/ )에서 홈 섹션이 아닌 다른 섹션(경제, 사회, IT 등)의 (주요)기사 페이지 넘김(이전, 다음) 버튼 작동하지 않습니다.
확인해본 바 현가드 필터 내 코르셋 프라이버시 필터 부분에 statistics.js 차단하는데,
문제는 모바일 네이버 뉴스의 페이지 넘김 버튼을 클릭했을 때 호출하는 스크립트 코드가 statistics.js ( http://static.news.naver.net/mnews/resources/날짜_숫자/js/generated/statistics.js ) 에 포함되어 있더군요. 
그래서 모바일 네이버 뉴스에서 페이지 넘김 버튼이 작동하지 않습니다.

이 문제를 해결하기 위해 허용필터(ex: @@http://static.news.naver.net/mnews/resources/ )를 추가해야 하지 않을까 합니다.

**Comment by NativeHyun** [comment]
안녕하세요! 해당 자바스크립트 부분을 허용 필터에 추가하였고. Firefox에서 페이지 넘김 버튼의 정상 작동을 확인하였습니다. 또 문제가 있을 경우에는 언제든지 이슈에 등록해 주세요 :) 감사합니다!
